version: "3.8"

services:
  nextjs-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nodejs-server
    environment:
      - REACT_APP_API_URL=http://nodejs-server:4000
    networks:
      - app-network

  nodejs-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  ollama-llm:
    image: ollama/ollama
    container_name: ollama-llm
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 6G

volumes:
  ollama:

networks:
  app-network:
    driver: bridge