# Next.js Client Deployment & Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-client
  labels:
    app: nextjs-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-client
  template:
    metadata:
      labels:
        app: nextjs-client
    spec:
      containers:
      - name: nextjs-client
        image: talhaelmali/nextjs-client:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-client
spec:
  selector:
    app: nextjs-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000  # NodePort olarak belirttik
  type: NodePort  # LoadBalancer yerine NodePort kullanıyoruz