apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
  labels:
    app: nodejs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
      - name: nodejs-server
        image: talhaelmali/nodejs-server:latest
        ports:
        - containerPort: 4000
        env:
        - name: LLAMA_API_URL
          value: "http://ollama-llm:11434/api/generate"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-server
spec:
  selector:
    app: nodejs-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP